- name: get etcd logs
  gather_facts: no
  user: ubuntu
  become: yes
  hosts: etcds

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:

  - name: fetch etcd logs
    fetch:
      src:  "{{ remote_log_path }}/{{ item.etcdlocal.name }}.log"
      dest: "{{ local_log_path }}/{{ inventory_hostname}}.{{ item.etcdlocal.name }}.log"
      flat: yes
    when: item.hostname == inventory_hostname
    with_items:
       -  "{{ etcds }}"


- name: get controller logs
  gather_facts: no
  user: ubuntu
  become: yes
  hosts: controllers

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:

  - name: fetch controller logs
    fetch:
      src:  "{{ remote_log_path }}/{{ item.controllerlocal.name }}.log"
      dest: "{{ local_log_path }}/{{ inventory_hostname}}.{{ item.controllerlocal.name }}.log"
      flat: yes
    when: item.hostname == inventory_hostname
    with_items:
       -  "{{ controllers }}"

- name: get crm logs
  gather_facts: no
  user: ubuntu
  become: yes
  hosts: crms

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:

  - name: fetch crm logs
    fetch:
      src:  "{{ remote_log_path }}/{{ item.crmlocal.name }}.log"
      dest: "{{ local_log_path }}/{{ inventory_hostname}}.{{ item.crmlocal.name }}.log"
      flat: yes
    when: item.hostname == inventory_hostname
    with_items:
       -  "{{ crms }}"

- name: get dme logs
  gather_facts: no
  user: ubuntu
  become: yes
  hosts: dmes

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:

  - name: fetch dme logs
    fetch:
      src:  "{{ remote_log_path }}/{{ item.dmelocal.name }}.log"
      dest: "{{ local_log_path }}/{{ inventory_hostname}}.{{ item.dmelocal.name }}.log"
      flat: yes
    when: item.hostname == inventory_hostname
    with_items:
       -  "{{ dmes }}"


- name: get locsim logs
  gather_facts: no
  user: ubuntu
  become: yes
  hosts: locsims

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:
  - name: fetch locsim logs
    fetch:
      src:  "{{ remote_log_path }}/{{ item.locapisimlocal.name }}.log"
      dest: "{{ local_log_path }}/{{ inventory_hostname}}.{{ item.locapisimlocal.name }}.log"
      flat: yes
    when: item.hostname == inventory_hostname
    with_items:
       -  "{{ locsims }}"


- name: get toksim logs
  gather_facts: no
  user: ubuntu
  become: yes
  hosts: toksims

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:
  - name: fetch toksim logs
    fetch:
      src:  "{{ remote_log_path }}/{{ item.toksrvsimlocal.name }}.log"
      dest: "{{ local_log_path }}/{{ inventory_hostname}}.{{ item.toksrvsimlocal.name }}.log"
      flat: yes
    when: item.hostname == inventory_hostname
    with_items:
       -  "{{ toksims }}"

