apiVersion: v1
kind: application
resource: fmbncisrs101.tacn.detemobil.de:5000/v2.0
metadata:
  kind: mex-app-qcow2
  name: testapp-vm
  tags: testapp-vm-tag
  tenant: testtenant
  operator: mex-gddt
spec:
  flags: force
  key: testapp-vm
  rootlb: testcluster.mex-gddt.mobiledgex.net
  image: http://registry.mobiledgex.net:8080/mobiledgex/cirros-0.4.0-x86_64-disk.img
  imageflavor: m1.tiny
  imagetype: ImageTypeQCOW
  proxypath: testapp-vm
  flavor: x1.medium
  uri: https://testapp.testcloudlet.mex-gddt.mobiledgex.net
  networkscheme: external-ip,external-network-shared,dhcp
  kubemanifesttemplate: 
